name: geofancing_app_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  native_geofence: ^1.0.3
  
  google_maps_flutter: ^2.10.0

  flutter_local_notifications: ^18.0.1

  # flutter_launcher_icons: ^0.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
     - assets/

# flutter_launcher_icons:
#   image_path: "assets/geofence_icon.png"
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   adaptive_icon_padding: true
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/geofence_icon.png"